// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA03pZXQYwlz5_pfMHMM94h2yj6CJgJjag',
    appId: '1:848370710077:web:68c9d706403cf0747b5c54',
    messagingSenderId: '848370710077',
    projectId: 'stockmaster-1f071',
    authDomain: 'stockmaster-1f071.firebaseapp.com',
    storageBucket: 'stockmaster-1f071.firebasestorage.app',
    measurementId: 'G-YZGQ6P159H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJc4EagbPEO462mbVLdesLxWGbA8KhQo',
    appId: '1:848370710077:android:af348729f44cf57b7b5c54',
    messagingSenderId: '848370710077',
    projectId: 'stockmaster-1f071',
    storageBucket: 'stockmaster-1f071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZZ9CnA2fkvPSF1v8WhCDlVf5sZpQYDA',
    appId: '1:848370710077:ios:b2f248898139c69d7b5c54',
    messagingSenderId: '848370710077',
    projectId: 'stockmaster-1f071',
    storageBucket: 'stockmaster-1f071.firebasestorage.app',
    iosBundleId: 'com.example.stockmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA03pZXQYwlz5_pfMHMM94h2yj6CJgJjag',
    appId: '1:848370710077:web:6b4edd17604125927b5c54',
    messagingSenderId: '848370710077',
    projectId: 'stockmaster-1f071',
    authDomain: 'stockmaster-1f071.firebaseapp.com',
    storageBucket: 'stockmaster-1f071.firebasestorage.app',
    measurementId: 'G-DLJB75MFW1',
  );
}
